{{HTML::script("js/jquery-1.8.3.min.js")}}
{{HTML::script("js/jquery-ui-1.10.3.custom.min.js")}}
{{HTML::script("js/jquery.ui.touch-punch.min.js")}}
{{HTML::script("js/bootstrap.min.js")}}
{{HTML::script("js/bootstrap-select.js")}}
{{HTML::script("js/bootstrap-switch.js")}}
{{HTML::script("js/flatui-checkbox.js")}}
{{HTML::script("js/flatui-radio.js")}}
{{HTML::script("js/jquery.tagsinput.js")}}
{{HTML::script("js/jquery.placeholder.js")}}
{{HTML::script("js/jquery.stacktable.js")}}
{{HTML::script("js/application.js")}}
</body>
</html>
